INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (1,'John','Smith','debito',NULL,NULL),(2,'John','Doe','credito',NULL,NULL),(3,'Pepe','Argento','paypal',NULL,NULL),(5,'Dardo','Fuseneco','paypal',NULL,NULL),(6,'Naruto','Uzumaki','debito',NULL,NULL),(8,'Pepe','Uzumaki','credito',NULL,NULL),(9,'Lou','Loe','paypal',NULL,NULL),(11,'son','gohan','mercadopago','2023-12-16 03:03:06','2023-12-16 00:00:00'),(12,'Son','Goten','debito','2023-12-17 03:00:16','2023-12-17 03:00:52');
INSERT INTO alumnos (id, nombre, apellido) VALUES (1, 'Marge', 'Simpson');
INSERT INTO alumnos (id, nombre, apellido) VALUES (2, 'Bart', 'Simpson');
INSERT INTO alumnos (id, nombre, apellido) VALUES (3, 'Lisa', 'Simpson');
INSERT INTO cursos (id, titulo, profesor) VALUES (1, 'Curso Spring', 'Andres');
INSERT INTO cursos (id, titulo, profesor) VALUES (2, 'Curso Java EE 9', 'Andres');
INSERT INTO direcciones(calle, numero) VALUES ('Av. Siempreviva', 742);
INSERT INTO direcciones(calle, numero) VALUES  ('Av. popo de perro', 782);
INSERT INTO tbl_clientes_direcciones(id_cliente, id_direccion) VALUES (1, 1);
INSERT INTO tbl_clientes_direcciones(id_cliente, id_direccion) VALUES (1, 2);
insert into clientes_detalles(prime, puntos_acumulados, cliente_detalle_id) values (true, 1000, 1);